language: python

sudo: false

python:
  - "2.6"
  - "2.7"
  - "3.0"
  - "3.1"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

cache:
  directories:
    - "$HOME/.pip-cache/"

install:
  - "pip install flake8"
  - "pip install coverage"
  - "pip install pytest-cov"
  - "pip install coveralls"

before_script:
  - "flake8 --max-line-length=140"

script:
  - "py.test --cov=."

after_success:
  - "coveralls"
