language: python

sudo: false

python:
  - "3.6"

cache:
  directories:
    - "$HOME/.pip-cache/"

install:
  - "pip install flake8 --cache-dir $HOME/.pip-cache"
  - "pip install coverage --cache-dir $HOME/.pip-cache"
  - "pip install coveralls --cache-dir $HOME/.pip-cache"

before_script:
  - "flake8 galena.py tests"

script:
  - "coverage run -m unittest discover"

after_success:
  - "coveralls"
