language: python

sudo: false

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - 3.5-dev
  - 3.6
  - 3.6-dev
  - 3.7-dev
  - nightly

install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 || $TRAVIS_PYTHON_VERSION == 3.2 || $TRAVIS_PYTHON_VERSION == 3.3 ]]; then
        pip install flake8==2.6.0;
    else
        pip install flake8;
    fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.2 ]]; then
        pip install coverage==3.7.1;
    else
        pip install coverage;
    fi
  - pip install pytest-cov
  - pip install coveralls
  - python setup.py install

before_script:
  - flake8 --max-line-length=140 galena/galena.py tests/*

script:
  - py.test --cov=.

after_success:
  - coveralls
